### ISSUE TITLE
进入网站以后不知道各部分都有什么用，建议放一个简单的介绍

### ISSUE THREAD

**Issue by mingMelody** [Re-Li-fe/OSS-Security-Risk-Analysis#2]

**Comment by Extord1108** [comment]
后续版本会在网站上补充一个说明，也可以先看看我们的[设计文档](https://blog.csdn.net/weixin_47231648/article/details/127876587)

**Comment by Extord1108** [comment]
在新的提交里 #10 已经在网站右上角补充了一个说明，介绍了网站的用途
