### ISSUE TITLE
readme和/docs里的内容是不是需要更新一下？

### ISSUE THREAD

**Issue by u2piaaa** [Re-Li-fe/OSS-Security-Risk-Analysis#3]
readme里的介绍和仓库的文件似乎不对应
![NOIX(RQ`HL J}1ES}MWHWOY](https://user-images.githubusercontent.com/53329948/207076385-7779ce6d-8f2d-4984-a8a0-96b7e94e6e93.png)

**Comment by Extord1108** [comment]
目前刚刚完成开发，文档还在撰写和修改

**Comment by Extord1108** [comment]
现在新的文档已经上传了，可以查看一下
