### ISSUE TITLE
想问下网站的统计数据是从哪里来的

### ISSUE THREAD

**Issue by Twosugar666** [Re-Li-fe/OSS-Security-Risk-Analysis#5]

**Comment by Extord1108** [comment]
npm包管理器是基于CouchDB数据库搭建的，可以直接使用[CouchDB的接口](http://guide.couchdb.org/draft/recipes.html#slow)请求信息。npm官方也提供了详细的[接口文档](https://github.com/npm/registry/tree/master/docs)。
