### ISSUE TITLE
数据库权限问题

### ISSUE THREAD

**Issue by CoderX-820** [Re-Li-fe/OSS-Security-Risk-Analysis#8]
能否开放数据库的操作权限

**Comment by Extord1108** [comment]
开放操作权限需要暴露数据库的ip和端口，肯定是不安全的。如果想实现一个新的接口的话可以看看我们[项目设计文档](https://blog.csdn.net/weixin_47231648/article/details/127876587)里的数据库设计，实现完接口后交给我们的开发者测试，或者告诉我们你想查询什么样的数据，我们给你提供接口。
